INSERT INTO COURSE (ID, AUTHOR, NAME) VALUES (10001, 'Joel', 'Java Course');
INSERT INTO COURSE (ID, AUTHOR, NAME) VALUES (10002, 'Joel', 'Angular Course');
INSERT INTO COURSE (ID, AUTHOR, NAME) VALUES (10003, 'Joel', 'Spring Course');
INSERT INTO COURSE (ID, AUTHOR, NAME) VALUES (10004, 'Joel', 'React Course');